version: '3'
services:
  apache-u24:
    build:
      context: .
      dockerfile: image/apache.dockerfile
    container_name: apache-u24
    ports:
      - '8000:80'
    environment:
      ID: apache-u24
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M

